# Generated by Django 5.0.4 on 2024-04-26 06:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuyenSinh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updates_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='banner/%Y/%m/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
            ],
        ),
        migrations.RenameField(
            model_name='khoa',
            old_name='description',
            new_name='introduction',
        ),
        migrations.AddField(
            model_name='khoa',
            name='program_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Tư vấn viên'), (2, 'Thí sinh')], default=2),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updates_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThiSinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('gender', models.IntegerField(choices=[(0, 'Nam'), (1, 'Nữ')], default=0)),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.ImageField(upload_to='thiSinh/%Y/%m/')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TuVanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('gender', models.IntegerField(choices=[(0, 'Nam'), (1, 'Nữ')], default=0)),
                ('email', models.EmailField(max_length=254)),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tuyenSinh.khoa')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TuyenSinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Tuyển sinh hệ chính quy'), (1, 'Tuyển sinh hệ liên thông'), (2, 'Tuyển sinh thạc sĩ'), (3, 'Tuyển sinh cao học'), (4, 'Tuyển sinh đào tạo từ xa')], default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('introduction', models.TextField()),
                ('diem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tuyenSinh.diem')),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tuyenSinh.khoa')),
            ],
        ),
        migrations.CreateModel(
            name='TinTuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updates_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('tuyenSinh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tuyenSinh.tuyensinh')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diem_Khoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updates_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('diem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tuyenSinh.diem')),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tuyenSinh.khoa')),
            ],
            options={
                'unique_together': {('khoa', 'diem')},
            },
        ),
    ]
