# Generated by Django 5.0.4 on 2024-06-14 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuyenSinh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
