# Generated by Django 5.0.4 on 2024-05-31 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuyenSinh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binhluan',
            options={'verbose_name': 'Bình luận', 'verbose_name_plural': 'Bình luận'},
        ),
    ]
