# Generated by Django 5.0.4 on 2024-06-03 04:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuyenSinh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuyensinh',
            name='diem',
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
