# Generated by Django 5.0.4 on 2024-05-29 15:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuyenSinh', '0002_alter_thisinh_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuvanvien',
            options={'verbose_name': 'Tư vấn viên', 'verbose_name_plural': 'Tư vấn viên'},
        ),
        migrations.AlterField(
            model_name='khoa',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
