# Generated by Django 5.0.4 on 2024-05-31 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuyenSinh', '0002_alter_binhluan_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tintuc',
            options={'verbose_name': 'Tin tức', 'verbose_name_plural': 'Tin tức'},
        ),
        migrations.AlterModelOptions(
            name='tuyensinh',
            options={'verbose_name': 'Tuyển sinh', 'verbose_name_plural': 'Tuyển sinh'},
        ),
    ]
