# Generated by Django 5.0.4 on 2024-05-29 15:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuyenSinh', '0003_alter_tuvanvien_options_alter_khoa_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khoa',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
