# Generated by Django 5.0.4 on 2024-05-31 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuyenSinh', '0004_alter_khoa_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='admin_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diem_khoa',
            name='diem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diem_diem', to='tuyenSinh.diem'),
        ),
        migrations.AlterField(
            model_name='diem_khoa',
            name='khoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diem_khoa', to='tuyenSinh.khoa'),
        ),
        migrations.AlterField(
            model_name='tuvanvien',
            name='khoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='khoa', to='tuyenSinh.khoa'),
        ),
    ]
