# Generated by Django 5.0.4 on 2024-06-15 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuyenSinh', '0005_question_answered_at_question_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='thisinh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='tuvanvien_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuvanvien_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
