# Generated by Django 5.0.4 on 2024-06-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuyenSinh', '0007_alter_answer_options_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id'], 'verbose_name': 'Câu trả lời', 'verbose_name_plural': 'Câu trả lời'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'Câu hỏi', 'verbose_name_plural': 'Câu hỏi'},
        ),
    ]
