# Generated by Django 5.0.4 on 2024-06-15 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuyenSinh', '0008_alter_answer_options_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='tuvanvien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
