# Generated by Django 5.0.4 on 2024-06-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuyenSinh', '0009_alter_answer_tuvanvien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tuvanvien_answer',
        ),
    ]
