# Generated by Django 5.0.4 on 2024-06-15 19:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuyenSinh', '0011_remove_question_answered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
